spring.application.name=fordcare-api

#spring.datasource.url=jdbc:postgresql://localhost:5432/fordcare_db
#spring.datasource.username=postgres
#spring.datasource.password=2101

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fordcare_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2101}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Limites globais de payload para reduzir risco de payload flooding
spring.servlet.multipart.max-request-size=2MB
spring.servlet.multipart.max-file-size=2MB

# Limite máximo para requisições form POST no Tomcat
server.tomcat.max-http-form-post-size=2097152

# HTTPS Configuration
server.port=8080

server.ssl.enabled=false
server.ssl.key-store=classpath:fordcare.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=fordcare